/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package blue;

public class App {

  private String getMessage() { return "My Gradle Project"; }

  public static void main(String[] args) {
    App app = new App();
    System.out.println(app.getMessage());
  }
}
